_BASE_: "Base-RCNN-MobileNet-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "https://www.dropbox.com/s/yduxbc13s3ip6qn/mobilenet_v2_detectron2.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 256
  RPN:
    POST_NMS_TOPK_TEST: 20    
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
